### ISSUE TITLE
Win32: ->spew_utf8 makes a locked file that blocks File::Temp dir removal

### ISSUE THREAD

**Issue by dolmen** [dagolden/Path-Tiny#100]
On Win32, when a file is created with `->spew_utf8` in a temporary directory created with `File::Temp::tempdir(CLEANUP => 1)`, File::Temp is not able to remove the directory at the end of the program.
Path::Tiny version 0.054, filesystem: NTFS, StrawberryPerl 5.18.2.1.

Test case: in Dist::Zilla 5.019, `t/diagnostic/plugin-fail.t`:

```
t/diagnostics/plugin-fail.t ... 1/?
cannot unlink file for C:\strawberry\cpan\build\Dist-Zilla-5.019-NQUcq1\tmp\DDYeVpnsl1\source\dist.ini: Permission denied at C:/strawberry/perl/lib/File/Temp.pm line 784.
cannot remove directory for C:\strawberry\cpan\build\Dist-Zilla-5.019-NQUcq1\tmp\DDYeVpnsl1\source: Directory not empty at C:/strawberry/perl/lib/File/Temp.pm line 784.
cannot remove directory for C:/strawberry/cpan/build/Dist-Zilla-5.019-NQUcq1/tmp/DDYeVpnsl1: Directory not empty at C:/strawberry/perl/lib/File/Temp.pm line 784.
t/diagnostics/plugin-fail.t ... ok
```

Cc: @rjbs

When looking at `->spew_utf8` code I see that the file is created locked, and I wonder if that is the reason of the lock that remains even after the file is closed.

**Comment by xdg** [comment]
There have been no additional reports of this and I don't foresee an opportunity to investigate, so I'm closing this ticket.  The timing of file removal on Windows is notoriously tricky and the initial error is `Permission denied` so this is unlikely to be a problem due to spew's locking.
