### ISSUE TITLE
Implement iterators for slurp/lines

### ISSUE THREAD

**Issue by dagolden** [dagolden/Path-Tiny#107]
A slurp iterator would read chunks of a file.  A lines iterator would return chunks of lines.

**Comment by eiro** [comment]
i was on my way to contribute on that as i would like to use it easily with Perlude (the current example is http://search.cpan.org/~marcc/perlude-0.61/lib/Perlude.pod#Path::Tiny). can i pull a request ?

**Comment by dagolden** [comment]
Sure!

**Comment by eiro** [comment]
the idea is to add stream as prefix for functions returning r filehandles... so filehandle would have a stream_filehandle counterpart. any mailling list to discuss abut it ?

**Comment by dagolden** [comment]
email dagolden at cpan dot org is fine.

I don't understand what you mean by stream counterparts.  It's possible what you want will wind up not being "::Tiny", but I'm happy to talk it over and see.

**Comment by xdg** [comment]
On reflection, I'm not implementing this as it's getting beyond the scope of Tiny.  Complex use cases can always be implemented directly with filehandles.
