### ISSUE TITLE
feature request: Parent $path->tempfile or $path->tempdir underneath $path

### ISSUE THREAD

**Issue by mlawren** [dagolden/Path-Tiny#115]
Path::Tiny accepts `$tmpfile = $path->tempfile` but the resulting temporary object is (non-obviously in my opinion) independently located underneath $TMP (or equivalent) instead of underneath the original `$path`.

**Comment by polettix** [comment]
I've come in the issues to look exactly for this.

Please shame me if I don't contribute a PR with test, code and documentation, or I find out that's not possible without breaking the current interface - possibly during the [Hacktoberfest 2021][] :smile:

[Hacktoberfest 2021]: https://hacktoberfest.digitalocean.com/

**Comment by mlawren** [comment]
Closing as this has been implemented. Thanks Flavio for the efforts!
