### ISSUE TITLE
Support IO/GLOB refs

### ISSUE THREAD

**Issue by ghost** [dagolden/Path-Tiny#116]
Since I keep seeing people recommend File::Slurp users should switch to Path::Tiny, I think the it should support one of the simplest features to ease their transition- the ability to read from IO/GLOB refs:

```
# people often forget how to do this properly
my $data = do { local $/; scalar <DATA> };

# easy to remember
my $data = read_file \*DATA;

# this would be ideal
my $data = path(\*DATA)->slurp;
```

**Comment by rollor** [comment]
> Path::Tiny is specifically all about paths and a glob doesn't have that information with it

Don't they have an implied path of  `path(__FILE__)->absolute`

**Comment by ap** [comment]
Uhm… I guess in some philosophical sense they do? But what does that fact help?
