### ISSUE TITLE
File::ReadBackwards

### ISSUE THREAD

**Issue by kablamo** [dagolden/Path-Tiny#118]
How would feel about a pr which adds File::ReadBackwards functionality similar to https://metacpan.org/pod/distribution/IO-All/lib/IO/All.pod#Reading-Backwards ?

I guess the UI would be like this
```
my @tail = $file->lines({ count => -10 }); # get the last 10 lines of the file
```

Or maybe
```
my @tail = $file->lines({ tail => 10 }); # get the last 10 lines of the file
```

**Comment by dagolden** [comment]
I'm mildly skeptical, but I'm willing to consider it if it's compact enough.  I lean towards `count => -10` (but could be convinced otherwise) and would want them to come in order (like unix tail) rather than reversed like ReadBackwards.
