### ISSUE TITLE
bug: slurp hangs when reading from File::Temp file

### ISSUE THREAD

**Issue by y** [dagolden/Path-Tiny#119]
slurp hangs when reading from a temp file to which an external process has written. File::Slurp/er do not have this issue.

    #!/usr/bin/env perl
    use 5.012;
    use warnings;

    use File::Temp;
    use Path::Tiny;

    my $text = File::Temp->new(suffix => '.txt');
    `echo foobar > $text`;
    my $content = path($text)->slurp;
    say $content;

**Comment by dagolden** [comment]
It has nothing to do with the external process and everything to do with File::Temp.

I think this just requires better documentation.  The `slurp` function wants to lock a filehandle for reading, but File::Temp by default takes an exclusive lock.  So the example program deadlocks.

If you change File::Temp to not take the lock, it works fine

```
my $text = File::Temp->new(suffix => '.txt', EXLOCK => 0);
```
