### ISSUE TITLE
locking&race in spew

### ISSUE THREAD

**Issue by powerman** [dagolden/Path-Tiny#125]
What's the point in using locks in spew? https://github.com/dagolden/Path-Tiny/blob/master/lib/Path/Tiny.pm#L1412
If this is an attempt to avoid race with two processes use same temporary file name in spew() then it doesn't work: in this case first may create and flock file, then second open and block on flock, then first write/rename/unlock, and then second will write to *same* file, and then try to rename it again to current name.
If this isn't an attempt to avoid race - then it looks just redundant. Maybe it's needed for portability on some platforms?
BTW, I'm not sure how portable is this, but it's much more safe to use open with O_EXCL|O_CREAT to avoid this race condition bug.

**Comment by dagolden** [comment]
On reflection, it's probably unnecessary. I suspect one was there and the other added later.
