### ISSUE TITLE
touch example doesn't make sense

### ISSUE THREAD

**Issue by powerman** [dagolden/Path-Tiny#126]
Example with touch at https://metacpan.org/source/DAGOLDEN/Path-Tiny-0.061/lib/Path/Tiny.pm#L1544 doesn't really make sense - what's the point in touching file before replacing it with temporary file created by spew()?

**Comment by dagolden** [comment]
Good point.  It was more illustrative than actual, I suspect.  Possibly `->touch->slurp` would be a better example so as to slurp but not fail if the file doesn't exist.
