### ISSUE TITLE
consistent $fh->close

### ISSUE THREAD

**Issue by powerman** [dagolden/Path-Tiny#128]
What do you think, is it makes sense to handle $fh returned by filehandle() in more consistent way - i.e. get standard Path::Tiny exceptions on $fh->close? This can be implemented by monkey-patching IO::Handle::close and keeping relationship between $fh and related path() object (also will need to monkey-patch IO::Handle::DESTROY to delete path() object from memory when related $fh is gone).

Also it may make sense to implement same feature for IO::Handle's read/write functions, because not all print() errors can be detected later on close() - for example, if $fh is open read-only then print() will fail but next after print close will not fail.

This feature shouldn't have any side effects on existing code - if one didn't use Path::Tiny::filehandle then behaviour of his $fh won't change. There are may be slight performance penalty on calling one extra method wrapper and doing one "if" inside it, but if people use OO-style with filehandles they probably won't bother much about this.

I may implement this and make pull request, but this change will be invasive enough (will need to create global variable to keep fh->object relationship), so you may like to make it yourself or reject it at all, so it's better to ask first.

**Comment by dagolden** [comment]
That's an interesting idea. I wouldn't monkey patch IO::Handle, but possibly implement Path::Tiny::Handle as subclass of IO::Handle.  I need to think more about whether this is still "::Tiny" -- i.e. whether the benefits outweigh the costs.

**Comment by xdg** [comment]
On reflection, I don't think this has a place in Path::Tiny.  I could imagine a separate CPAN module that wraps a filehandle, along the lines of [IO::Wrap](http://p3rl.org/IO::Wrap) to do the sort of error checking you'd like.
