### ISSUE TITLE
Suggestion: a spewer that auto-creates parents sanely

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Path-Tiny#129]
There's a common pattern you'll see used a lot of, and it has a few pitfalls.
```perl
    path($foo)->parent->mkpath if -d  path($foo)->parent;
    path($foo)->spew( $content );
```
This is somewhat amusing because there's opportunity for an rmdir call between the two, leading to a fun race condition.

This problem was recently spotted here ( which is still using Path::Class, but the argument remains )

https://metacpan.org/source/RJBS/Dist-Zilla-5.032/lib/Dist/Zilla.pm#L643

This looks sane, until you look further back here:

https://metacpan.org/source/RJBS/Dist-Zilla-5.032/lib/Dist/Zilla/Dist/Builder.pm#L528

That is, immediately prior to calling mkpath in dzil, it does an rmtree.

So the real flow is:
     
         rmtree foo
         mkpath foo
         spew foo/Changes

This is fine on Unix. On windows however, `rmdir` is only advisory, and `rmdir` can return **success** while  not actually deleting the dir. ( Win32 processes can keep the directory alive even though they're marked for deletion, either delaying the delete till process closure or negating the delete entirely. You can even explicitly mark a for-deletion file as no-longer-for-deletion: http://www.osronline.com/article.cfm?article=245 )

So what in practice can happen on win32

         rmtree foo   # no errors
         mkpath foo  # no errors
         spew foo/Changes  # error, no permission to write to foo

But this is not really an expectation you have a magic wand to fix that, more that its common enough to do it this way, and it could be more resilient in the same way as that logic was applied to Test::TempDir::Tiny to avoid delete/create races.

( Perhaps for instance you could have a loop that attempts to mkdir/open fh a few times in a loop until open stops failing or reaches a counter )

Maybe even something like:

```perl
    path($foo)->spew({ create_parents => 1 }, $content );
```

**Comment by kentfredric** [comment]
```
04:16:23 < Mithaldu> mkdir foo
04:16:30 < Mithaldu> perl -e "opendir my $dh, 'foo'; sleep 999999"
04:16:51 < Mithaldu> debug: Path::Class::dir('foo')->rmtree
04:16:53 < Mithaldu> i got to
04:17:00 < Mithaldu> if (rmdir $root) {
04:17:11 < Mithaldu> $root is 'foo'
04:17:18 < Mithaldu> and rmdir succeeded
04:17:35 < Mithaldu> yet the sleeping perl clearly still has its lock
04:17:39 < Mithaldu> and the dir is still in my file manager
04:18:01 < Mithaldu> and rmtree returned success too, since it trusts rmdir in indicating success
04:18:14 < Mithaldu> now i kill the sleeping perl
04:18:18 < Mithaldu> and foo is gone
```

**Comment by dagolden** [comment]
This is inherently race prone and I don't think Path::Tiny should try to solve races as the solution is user-dependent.  For example, instead of rmtree, one could rename the directory out of the way, then remove it, and mkdir the replacement.  It's races all around, still, since there's no `O_CREAT|O_EXCL` equivalent for directories and even then there's a race between mkdir and opening a file in the directory.

So I don't think there is any "sane" way to do what you want.
