### ISSUE TITLE
Feature: allow checking path attributes at instantiation and throw error on failure

### ISSUE THREAD

**Issue by kbenson** [dagolden/Path-Tiny#130]
How amenable are you to allowing an optional hashref passed as the last item in path() that confirms the path matches some simple criteria (such as the exists and the is_* methods) or throws an error?  I would be happy to write the code myself and submit a pull request if you think it's worth while.

E.g.
path("/opt/some_dir", {is_dir=>1}); # OK
path("/opt/some_dir", {is_file=>1}); # throws error like "Supplied path does not match positive 'is_file' requirement
path("/opt/some_dir", {is_dir=>0}); # throws error like "Supplied path does not match negative 'is_dir' requirement
path("../some_dir", {is_absolute=>1,is_dir=>1}); # throws error like "Supplied path does not match positive 'is_absolute' requirement

I think that's clear, and will help clean up some validation code for a lot of people.

**Comment by dagolden** [comment]
I don't think attaching it to the constructor makes sense.  I might be open to an `assert` method that takes a code reference (or maybe a list of code references) that gets the path set in `$_` and has to return true or false.  E.g.

````
$obj = path( $whatever )->assert( sub { -r -w -x && $_->is_absolute } );
```

This would returns `$self` if the assertion passes or throw an error if it fails.  Or the coderef could throw its own error for something custom.

I think that's clearer, won't take much code, and is very customizable.

What do you think?

**Comment by kbenson** [comment]
Works for me.  Anything to reduce lines of code in a clear and concise
manner is a win IMO, and in the context of parameter validation, I think
this fits.

Want me to work something up and submit a pull request or did you have
something concrete you wanted too do (since you mentioned it wasn't much
code)?

**Comment by dagolden** [comment]
Please take a look at this commit and let me know what you think.

**Comment by kbenson** [comment]
Looks good to me, except for a typo in t/basic.t line 172 (s/acception/exception/).

Thanks!

**Comment by dagolden** [comment]
Darn late night coding!  Thanks for catching that typo.

I have a bunch of other PR's to add to Path::Tiny so this will get released "soon" but not necessarily today.

**Comment by kbenson** [comment]
sounds good! Thanks again!
