### ISSUE TITLE
option for fsync

### ISSUE THREAD

**Issue by powerman** [dagolden/Path-Tiny#133]
What do you think about adding `{fsync=>1}` option for some methods (like `spew()`)?

The idea is, if one wanna use files in atomic/transactional way, then it isn't enough to just write to temp file and then atomically rename it - we also need to do `fsync($tempfile)` between write and rename, and (I'm not 100% sure) probably also need to do `fsync($target_dir)` after rename. This will slowdown, but AFAIK it's only way to really guarantee this data will be later read from file with given name after successful return from `spew()` even in case of server hang/reset (except when HDD or filesystem dies, of course).

**Comment by dagolden** [comment]
`fsync` operates only on file descriptors, not files.  If there was such an option, it would only work on the temp filehandle of spew before the rename.

My inclination is this going to be a very rarely used feature and doesn't fit into the 80/20 coverage philosophy of Tiny.  I'll keep this ticket open in case I reconsider, however.

**Comment by xdg** [comment]
On further reflection, getting this right portably could be tricky.  References:

* http://danluu.com/file-consistency/
* http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/
* http://thunk.org/tytso/blog/2009/03/15/dont-fear-the-fsync/
* https://lwn.net/Articles/351422/
* https://www.quora.com/What-should-a-developer-know-when-using-a-Unix-file-system
* https://www.lucas-nussbaum.net/blog/?p=701

One possible conclusion is not to do this -- the rename is atomic, but not guaranteed durable, which is probably sufficient for a ::Tiny module.

**Comment by xdg** [comment]
Per the previous comment, closing as "won't fix".
