### ISSUE TITLE
Accidental "Not a SCALAR reference" when visitor returns a non-scalar ref

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Path-Tiny#143]
Reduced example:

```perl
use strict;
use warnings;
use Path::Tiny;

path('/tmp')->visit(sub {
  {}
});
```
```
Not a SCALAR reference at /home/kent/perl5/perlbrew/perls/5.22.0/lib/site_perl/5.22.0/Path/Tiny.pm line 1729.
```

Of course, this can happen when you're doing anything and not explicitly returning a value and just *happening* to have the last statement return a hashref.

**Comment by kentfredric** [comment]
A much more subtle example that mimics this enjoyable fun:
```perl
path('/tmp')->visit(sub {
    my ( $path, $state ) = @_;
    $state->{$path} = $path->relative('/tmp');
});
```

**Comment by dagolden** [comment]
Is this with the latest development version that is supposed to fix that
bug?

**Comment by kentfredric** [comment]
Ah. No. =). 0.068 =). Hadn't spotted the -dev

**Comment by kentfredric** [comment]
Yeah. Fixed in '069.
