### ISSUE TITLE
Unrecognized option(s) passed to make_path

### ISSUE THREAD

**Issue by madsen** [dagolden/Path-Tiny#144]
Path::Tiny's `mkpath` method passes an `err` option to File::Path's `make_path` function.  However, the correct name of that option is `error`.  The newest File::Path is now checking its arguments for validity.

**Comment by madsen** [comment]
For example, [this failure report](http://www.cpantesters.org/cpan/report/b577cf68-2caa-11e5-81eb-19d5ddb78640).  (Although I think that was using a development version that croaked on this error.  The release version uses `carp` because of problems like this.)

**Comment by dagolden** [comment]
Already addressed in https://metacpan.org/release/DAGOLDEN/Path-Tiny-0.071-TRIAL.

I'll leave this open until the stable ships.

**Comment by madsen** [comment]
Sorry, I checked for a new release, but didn't notice the trial one.

**Comment by genehack** [comment]
Any idea when this will get released?

**Comment by dagolden** [comment]
Shipped to CPAN as 0.072.

**Comment by genehack** [comment]
thanks!
