### ISSUE TITLE
Path::Tiny does not support subclassing.

### ISSUE THREAD

**Issue by van-de-bugger** [dagolden/Path-Tiny#146]
$ cat test.pl
    #!/usr/bin/perl
    use strict;
    use warnings;
    use Scalar::Util qw{ blessed };
    package Path::Tiny::Subclassed {
        use Path::Tiny qw{};
        use parent 'Path::Tiny';
    };
    my $path = Path::Tiny::Subclassed->new( '.' );
    print( blessed( $path ), "\n" );
    
    $ ./test.pl
    Path::Tiny

I would expect `$path` is blessed to `Path::Tiny::Subclassed`.

**Comment by dagolden** [comment]
That's an intentional design decision for speed (i.e. avoiding method call overhead) and because the implementation is array-based and subclasses have nowhere safe to store state, but it should be better documented.
