### ISSUE TITLE
request: method to return path quoted for shell usage

### ISSUE THREAD

**Issue by y** [dagolden/Path-Tiny#147]
I often have to feed the path to a shell call and it would be helpful if there were a method to call to do the proper quoting/escaping of the path.

**Comment by dagolden** [comment]
Shell quoting is a horribly complicated topic that is hard to get right portably and I wouldn't want to take that on as part of Path::Tiny.

I would encourage you to use CPAN modules dedicated to the task, such as String::ShellQuote and Win32::ShellQuote instead.
