### ISSUE TITLE
Make callback sub for visit() Sub::Quote aware

### ISSUE THREAD

**Issue by sjmiller** [dagolden/Path-Tiny#148]
Sort of a goofy edge case, which may make it not suitable for a tiny module, but I want to be able to use Path::Tiny with Object::Remote. The two things sort of preventing this are the requirement of a newish File::Spec and visit() being unusable since coderefs aren't serializable.

Providing the callback in string form and having visit() recognize it and convert it into a coderef via Sub::Quote (if installed) would be helpful.

**Comment by dagolden** [comment]
I don't think it's right for Path::Tiny.  Your code can use Sub::Quote and create the coderef argument without Path::Tiny changing at all:

    $path->visit( qsub q{ ... } )
