### ISSUE TITLE
The copy and move methods should take multiple arguments that imply path constructor

### ISSUE THREAD

**Issue by robrwo** [dagolden/Path-Tiny#157]
I often find myself writing something like

``` perl
$path->move($foo, 'bar/baz');
```

when I mean

``` perl
$path->move( path($foo, 'bar/baz') );
```

It would be nice to have that sort of syntactic sugar for the copy and move methods.

**Comment by xdg** [comment]
I don't think I like the idea of joining multiple arguments in case I ever want to add optional arguments, but I'm open to a PR to throw an exception if there are too many arguments.

**Comment by robrwo** [comment]
For consistency with other methods, the options could be a hash reference that occurs as the first argument.  So the methods could ignore that, even if there are currently no options for it.

**Comment by xdg** [comment]
On reflection, no other methods that don't take an options hashref validate against extra arguments, so I'm going to close this issue as a won't fix.
