### ISSUE TITLE
A prepend method would be convenient

### ISSUE THREAD

**Issue by robrwo** [dagolden/Path-Tiny#158]
It would be useful to have a prepend method, that is equivalent to something like
```perl
sub prepend {
  my $self = shift;
  my $tmp = Path::Tiny->tempfile;
  $tmp->append( { truncate => 1 }, @_, $self->slurp);
  $tmp->move($self);
}
```

**Comment by xdg** [comment]
For that, why not just `$path->spew( $stuff, $path->slurp )`?  I think you get the same atomicity properties (or rather, the same race between slurping and writing/moving).

I think for a "safe" prepend, you'd actually need to open a locked r/w handle, read everything then rewind and write the new stuff and the old stuff.

**Comment by robrwo** [comment]
Yes, I think would be a better idea.
