### ISSUE TITLE
touch dies on files that you have group write access to

### ISSUE THREAD

**Issue by ggl** [dagolden/Path-Tiny#174]
A `$path->touch` call dies on group writable files regardless if you belong to the group that has write access on the file. This is because `utime` does not allow you to set a (specific) modification time or an access time if you do not own the file but will happily set the current time with these arguments undef.

Create the file and set the proper permissions:
    # touch /tmp/test.tmp
    # chown root:staff /tmp/test.tmp
    # chmod 0664 /tmp/test.tmp

Now run this code under user `bob` group `users`; `bob` also belongs to group `staff`.

    $ su - bob
    $ perl -MPath::Tiny -e '$epoch = time(); print utime(undef, undef, "/tmp/test.tmp")'
    1
    $ perl -MPath::Tiny -e '$epoch = time(); print utime($epoch, $epoch, "/tmp/test.tmp")'
    0
    $ perl -MPath::Tiny -e '$epoch = time(); path("/tmp/test.tmp")->touch
    Error utime (1463483185) on '/tmp/test.tmp': Operation not permitted at -e line 1

Path::Tiny->touch insists on explicitly setting the `$epoch` to `time()` even though no such argument was passed to it in the first place.

**Comment by xdg** [comment]
Thanks!
