### ISSUE TITLE
`tempfile`'s not cleaned up on ^C

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Path-Tiny#181]
```perl
use strict;
use warnings;

use Path::Tiny;

my $file = Path::Tiny->tempfile('LOOK-FOR-ME-XXXXXX', suffix => '.txt' );
while(1) { }
```

```bash
perl test.pl
^C
ls /tmp/LOOK-*
# /tmp/LOOK-FOR-ME-cjEE75.txt
```

This seems in conflict with documentation:

> Think of what "Path::Tiny" gives you to be just a temporary file name that gets cleaned up.

**Comment by xdg** [comment]
I think it goes without saying that you interrupt the program, the program will not clean up for you.  Just like if you SIGINT in the middle of a long `spew`, you'll get a partial file.

**Comment by kentfredric** [comment]
Ugh. I guess I misremembered how global destruction works. :/ 

Anyone else who has this bug needs to `$SIG{INT} = sub { die  }` somewhere important, and that's clearly  not something that can be done in File::Temp or Path::Tiny
