### ISSUE TITLE
error opendir at the foreach $file ($parentfile->children) if a child is not accessible (permission denied)

### ISSUE THREAD

**Issue by kbntk** [dagolden/Path-Tiny#182]
While running the foreach loop:

`foreach my $file ($dir->children){`
if one of the children files cannot be readable due to permission denied error, then the whole loop stops and this error is thrown:

`Error opendir on '/home/kitchen/freezor/vodka': Permission denied at ./party_in.pl line 2230.`

Do you have any idea how I could handle this, so in case this error happens, the loop will continue with accessing the next child instead of exiting?

One solution could be to have an option (filter) that allows only children that do not cause this error to be returned by the `children` function.

**Comment by xdg** [comment]
Assuming that the error is on the `$dir->children`, you could do either of these perhaps:

```
foreach my $file( -r $dir && $dir->children ) { ... }

foreach my $file ( eval { $dir->children } ) { ... }
```

But you mentioned "if one of the children files...the whole loop stops".  If something is happening with `$file`, you need to show me what you're doing with `$file` because I don't see where the `Error opendir` message would come from otherwise.

**Comment by kbntk** [comment]
Hi xdg,

your explanation helped me. I'm now using `eval` and the problem doesn't happen anymore. 

In case you are still interested in the inner code:

```
use Try::Tiny;
(...)
foreach my $file (eval {$dir->children}){ 
	try {
		say "file: ". $file;
		if($file->is_dir) {
			say $fh_dirs_not_processed $file;
			next;
		}
		my $stat= $file->stat; 
		say $stat;
		say $fh_files $file ."  " . $stat->size;
	}
	catch {
		 warn "File $file problem in the foreach loop";
	}
}
```

**Comment by kbntk** [comment]
Hi xdg,

your explanation helped me. I'm now using `eval` and the problem doesn't happen anymore. 

In case you are still interested in the inner code:

```
use Try::Tiny;
(...)
foreach my $file (eval {$dir->children}){ 
	try {
		say "file: ". $file;
		if($file->is_dir) {
			say $fh_dirs_not_processed $file;
			next;
		}
		my $stat= $file->stat; 
		say $stat;
		say $fh_files $file ."  " . $stat->size;
	}
	catch {
		 warn "File $file problem in the foreach loop";
	}
}
```
