### ISSUE TITLE
tempdir()->realpath() loses File::Temp::Dir object

### ISSUE THREAD

**Issue by autarch** [dagolden/Path-Tiny#183]
```
$ perl -MPath::Tiny=tempdir -E 'my $t = tempdir()->realpath;  say $t; say $t->is_dir ? 1 : 0'
/tmp/uuAcgiAxVG
0
```

The object returned by realpath no longer contains a reference to the File::Temp::Dir object, so the directory is cleaned up. It seems like the underlying tempdir object should be preserved across calls to `realpath` and `absolute` (and maybe other methods?). Of course, then there's a new problem that the tempdir won't be cleaned up until _all_ the objects go out of scope.

At the very least, this could probably use a warning in the docs.

**Comment by autarch** [comment]
Alternatively, if `tempdir()` could be told to simply do the `realpath` call internally before returning, that might be the best solution.

**Comment by xdg** [comment]
Do you really need `realpath` vs the existing `absolute`?  Seems like a real edge case.

**Comment by xdg** [comment]
It's preserved across `absolute` because it's already absolute.

On the one hand, preserving across `realpath` feels like it would be harder to reason about lifetime, but I suppose it's no worse than having multiple copies of the path object itself.

**Comment by xdg** [comment]
Another option could be like this, specifying it as an option on construction:

```
my $t = Path::Tiny::tempdir( { realpath => 1 }, @file_temp_options );
```

That would be consistent with a lot of the rest of the Path::Tiny API.

**Comment by autarch** [comment]
This last suggestion would be ideal. As for whether I need it, the answer is yes. I'm trying to compare paths coming back from code that calls `realpath` with a path  I passed in. The path I passed in is created as a tempdir.

**Comment by xdg** [comment]
Shipping a TRIAL dist to CPAN shortly.
