### ISSUE TITLE
Make TO_JSON as an alias of stringify

### ISSUE THREAD

**Issue by bpj** [dagolden/Path-Tiny#186]
I think this would DWIM in most cases. Currently I usually monkey patch it but I feel a little guilty about that.

**Comment by xdg** [comment]
Thank you for the suggestion.  I've considered this before but haven't decided if users should be explicit about their intent.

**Comment by bpj** [comment]
The only situation I can think of where you wouldn't want to stringify a P::T object as the path when converting to JSON would be when you would want it to become something like `{"path_to_foo": "path/to/foo"}` and then the value will be the stringified path anyway. I briefly considered a situation where you'd want the realpath, but in most cases it would anyway make most sense to explicitly ascertain the realpath at the decoding end, since often the path will be to some file which has been transmitted along with the JSON, e.g. in an archive so that the path in the JSON is relative to the 'root' of the uncompressed archive. If I dare say it a pair of accessors `stringify_as_realpath($bool)` and `stringify_relative_to($path)` might be generally useful.

**Comment by ap** [comment]
`TO_JSON` has been identical to `stringify` (though only just became an actual alias) since 9b8a19b7b4911bb6e03266829a01b182e7d76434? Which was released in 2014. I’m confused about what this ticket is for…

**Comment by xdg** [comment]
Just missed it at the time, I guess.  Closing.
