### ISSUE TITLE
support unlink_on_destroy for File::Temp objects

### ISSUE THREAD

**Issue by spazm** [dagolden/Path-Tiny#187]
Sometimes I want to save a temporary file for manual inspection after a unit test fails.

Normally I want my temporary files and directories to be destroyed during clean-up, which is the default behavior for `File::Temp` objects created by `Path::Tiny`.  If I decide I want to change that behavior based on runtime behavior, it's too late to pass in arguments `{UNLINK=>0}` or `{CLEANUP=>0}` to the constructor.  Setting `$File::Temp::KEEP_ALL` seems like too broad a stroke.

I'd like some method on a `Path::Tiny` object to call to access the `unlink_on_destroy` method on the `File::Temp` object stored in `Path::Tiny::TEMP`.  A bonus is that directories and files both support the same method.

Perhaps something like the following.  Possibly with some error handling if TEMP isn't defined?
```.perl
sub unlink_on_destroy {
    my $self = shift;
    $self->[TEMP]->unlink_on_destroy(@_)
}
```

This seems cleaner than the encapsulation violating code I just put in my test to modify the `Path::Tiny::TEMP` element of the `Path::Tiny` object.

```.perl
my $test_file = Path::Tiny->tempfile(...);
if ($error_condition) {
  diag "saving output file for inspection" . $test_file;
  $test_file>[Path::Tiny::TEMP]->unlink_on_destroy( 0 );
}
```

**Comment by xdg** [comment]
I don't want to proxy all File::Temp methods.  My thought at the moment is to just add an accessor to the stored object.

**Comment by spazm** [comment]
sweet!  Thanks.
