### ISSUE TITLE
`move` does not return documented value on failure

### ISSUE THREAD

**Issue by osfameron** [dagolden/Path-Tiny#189]
The docs suggest that `move` 'Returns the result of the "rename" function', but on failure to rename, it actually throws an exception.

(I'd actually prefer the documented behaviour for this case fwiw, but I suppose simpler/compatible to just update docs)

**Comment by xdg** [comment]
The docs now say that an exception is thrown on failure.  

Also, FWIW, #260 is going to change the return to work like  `copy` returning the new location as an object.
