### ISSUE TITLE
Path::Tiny fails to install via cpanm on 5.24.1

### ISSUE THREAD

**Issue by ravenhall** [dagolden/Path-Tiny#193]
Path::Tiny fails to install via cpanm on 5.24.1 with error "Module 'open' is not installed."
I have attached a cpanm log showing verbose output.
[path-tiny-errors.txt](https://github.com/dagolden/Path-Tiny/files/1027706/path-tiny-errors.txt)

**Comment by xdg** [comment]
What version of cpanm?  What's your `perl -V`.  What version of ExtUtils::MakeMaker?  Since `open` is a core perl module, that it can't be found is a likely a sign that something is wrong in your toolchain.

**Comment by brainbuz** [comment]
Path::Tiny has been passing the CPAN smokers on 5.24.1 and also 5.26.0 and 5.27.x, it looks like this issue was specific to ravenhall's system and not to Path::Tiny.

**Comment by xdg** [comment]
With no followup details in a month, I'm going to go ahead and close the ticket.

**Comment by ravenhall** [comment]
Sorry for my late response. Real life blew up on me.
It may very well be my perl install rather than the module itself, so it's fine to leave this closed. I'll troubleshoot it more and probably find that it is on my side. If I find otherwise, I'll submit a better issue report with more details.

I'm including the details you asked for just as an FYI.  
cpanm (App::cpanminus) 1.7043 on perl 5.024000 built for x86_64-linux-thread-multi
ExtUtils::MakeMaker: 7.1002 
[Perl-V.txt](https://github.com/dagolden/Path-Tiny/files/1106230/Perl-V.txt)

**Comment by dzhengfy** [comment]
@ravenhall , did you remember how you fix this issue finally? Now I have similar issue.
cpanm -v Path::Tiny  
...
==> Found dependencies: open
Searching open (0) on cpanmetadb ...
skipping S/SH/SHAY/perl-5.26.2.tar.bz2
! Installing the dependencies failed: Module 'open' is not installed
! Bailing out the installation for Path-Tiny-0.104.

**Comment by shlomif** [comment]
On Thu, 07 Jun 2018 06:05:37 -0700
dzhengfy <notifications@github.com> wrote:

> @ravenhall , did you remember how you fix this issue finally? Now I have
> similar issue. cpanm -v Path::Tiny  
> ...
> ==> Found dependencies: open  
> Searching open (0) on cpanmetadb ...
> skipping S/SH/SHAY/perl-5.26.2.tar.bz2
> ! Installing the dependencies failed: Module 'open' is not installed
> ! Bailing out the installation for Path-Tiny-0.104.

What are your os/perl/etc. versions and distros? open has been a core module
since perl 5.6.0.

> 
> 



-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Selina Mandrake - The Slayer (Buffy parody) - http://shlom.in/selina

I used to be arrogant. Now I’m simply perfect.
    — one of Shlomi Fish’s relatives, http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
