### ISSUE TITLE
`copy` and `move` should handle tilde like `path`

### ISSUE THREAD

**Issue by y** [dagolden/Path-Tiny#197]
It is unexpected that you can't do:

    path("~/Desktop/foo.txt")->copy("~/Desktop/bar.txt");

and must instead do:

    path("~/Desktop/foo.txt")->copy("/Users/y/Desktop/bar.txt");

Tilde globbing should be consistently applied wherever a raw path is required.

**Comment by ap** [comment]
Note that in the meantime  (or later to not bump your Path::Tiny dep) you can work around this by doing

```perl
path("~/Desktop/foo.txt")->copy(path "~/Desktop/bar.txt");
```

**Comment by xdg** [comment]
I've created a branch – https://github.com/dagolden/Path-Tiny/tree/issue-197-copy-move-tilde – but I don't have time to write the tests for it.  If you can write tests that pass on Unix and Windows, I'd be happy to merge this in.

**Comment by xdg** [comment]
On reflection, I've decide that trying to extend tilde expansion to this and other parts of the API is too hard to do consistently and that the very existence of tilde expansion is a bug factory.  I'm commiting a change to deprecate tilde expansion and document the limitation that only `path` expands tildes and other method arguments do not.
