### ISSUE TITLE
Wishlist: a spew_on_diff_content() method/feature

### ISSUE THREAD

**Issue by shlomif** [dagolden/Path-Tiny#200]
Hi!

Here - https://github.com/shlomif/shlomi-fish-homepage/blob/master/lib/Shlomif/Out.pm - I wrote two functions that accept a path object and text, and write the text only if it is different than the current content of the file (to avoid updating the mtime - for make and other build systems). Do you think this use case will make a  good new feature for Path-Tiny?

**Comment by xdg** [comment]
That sounds outside the bounds of Path::Tiny itself, but you could certainly use Path::Tiny as part of an independent CPAN solution.  Sounds handy for certain situations.

**Comment by shlomif** [comment]
On Wed, 27 Dec 2017 08:40:08 -0800
David Golden <notifications@github.com> wrote:

> That sounds outside the bounds of Path::Tiny itself, but you could certainly
> use Path::Tiny as part of an independent CPAN solution.  Sounds handy for
> certain situations.
> 

OK, thanks for letting me know what you think. I'll proceed that way.

Regards, -- Shlomi

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Buffy Factoids - http://www.shlomifish.org/humour/bits/facts/Buffy/

It is impossible to make anything foolproof because fools are so ingenious.
    — Source Unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .
