### ISSUE TITLE
Should escape File::Glob metacharacters before tilde expansion

### ISSUE THREAD

**Issue by regina-verbae** [dagolden/Path-Tiny#201]
The following example paths all cause an `uninitialized value $homedir in substitution` error when passing to `path`:

```
~path[123]
~path*
~path?
```

The following examples create the wrong path:

```
~path\\x
    # returns '~pathx'
~path{a}
    # return '~patha'
```

All metacharacters (besides `~`) used by File::Glob should be escaped before passing the path to `bsd_glob`.  Pull request forthcoming.

**Comment by xdg** [comment]
Fixed with d40a3bf and 139280c
