### ISSUE TITLE
Visit doesn't visit root folder

### ISSUE THREAD

**Issue by ambs** [dagolden/Path-Tiny#209]
This might be the desired behavior, but in that case, it would be great to document it.
If I ask Path::Tiny to visit /tmp, it will visit all its child, but not /tmp itself. And as expected, I can't ask Path::Tiny to visit / so that /tmp is included O:-)

Of course that is is only one file, that can be treated independently. But for me it feels odd. Thus, I would suggest to change its behavior or add a documentation note (I can do a PR, just let me know what side to lean to).

**Comment by xdg** [comment]
It's already documented: `Executes a callback for each child of a directory.`  I think I'm fine how it is, as the docs also point to Path::Iterator::Rule for a better iterator, anyway.
