### ISSUE TITLE
Problem of Path::Tiny in combination with Par::Packer (pp)

### ISSUE THREAD

**Issue by LiKneu** [dagolden/Path-Tiny#210]
I'm using strawberry perl 5.26.2 on Win 7
The version of Path::Tiny is 0.104
The version of pp is 0.992

I've packed a per script with pp into an exe file.
Trying to run the exe file generates the following error message:

>Can't locate if.pm in @INC (you may need to install the if module) (@INC contains: C:\Users...
...CODE(0x2b1759c) CODE(0x2b17794)) at Path/Tiny.pm line 119.
BEGIN failed--compilation aborted at Path/Tiny.pm line 119.

I had a look into the Tiny.pm package and found the following in line 115 - 121

```perl
# flock doesn't work on NFS on BSD.  Since program authors often can't control
# or detect that, we warn once instead of being fatal if we can detect it and
# people who need it strict can fatalize the 'flock' category

#<<< No perltidy	# this is line 119
{ package flock; use if Path::Tiny::IS_BSD(), 'warnings::register' }
#>>>
```

Since I'm neither working with NFS nor BSD I commented out the line {package....} and everything works fine without any error messages.
Unfortunately my perl skilles are not sufficient to identify whether this line of code could be improved to prevent the above mentioned error message or pp or my code should be improved.

**Comment by xdg** [comment]
That sounds like a bug in Par::Packer.  The `if` module has been part of the Perl core since v5.6.2.
