### ISSUE TITLE
`mkpath` takes ownership options but `touchpath` does not

### ISSUE THREAD

**Issue by Altreus** [dagolden/Path-Tiny#218]
I have to do:

```
# for some $absfile
$absfile->parent->mkpath({ owner => $uid, group => $gid});
$absfile->touch->spew(...);
chown $uid, $gid, $absfile;
```

I'd rather do:

```
$absfile->touchpath({ owner => $uid, group => $gid })->spew(...);
```

**Comment by ap** [comment]
Both `touch` and `mkpath` take a parameter.

**Comment by ap** [comment]
With the benefit of retrospect I realize that the point of my reply is completely unclear: I had to figure out what I meant to say myself. Namely: considering that `touchpath` combines two methods which both take options, if it’s to take options to pass to one of them then it’s unclear which one to prioritize. (And if it’s to be able to pass options to both of them, then the question would be what a reasonable interface for that would look like.)

**Comment by xdg** [comment]
`touchpath` has added documentation suggesting using `mkdir` and `touch` separately if options are needed.  Closing.
