### ISSUE TITLE
A text based lookup for ->parent method

### ISSUE THREAD

**Issue by masterbee** [dagolden/Path-Tiny#219]
@xdg , first off great work on the module , I stumbled up in via the great reference you got from Perl Maven [https://perlmaven.com/how-to-add-a-relative-directory-to-inc]. After a few minutes of playing with it, I simply could not use anything else. Well done!

That said, I am now often using this module and its nifty parent feature to set things like a relative lib folder location. So in order to streamline the parent lookup I was wondering if there was an appetite to add a "text" lookup instead of numeric only?

I have a suggested P.R. where I created a new function called "closest" that does simply crawls up the parent ladder and matches the ```basename``` of the directory with that value passed and returns a ```Path::Tiny``` object.

I am not sure if the function name was the best fit, but heck jQuery did it 😝  

@szabgab  - you may want to update your article with this feature if it gets implemented. It makes things quiet a bit cleaner and more robust for relative locations of libs for developers IMHO. Food for thought and great articles, love Perl Maven!

**Comment by ap** [comment]
I don’t see any part of the code in @szabgab’s article that can be simplified using this…?

More generally, I can think of examples of code wanting to go up a variable number of directories, but not a single case where the criterion for where to stop was the *name* of the parent directory. Every example I can think is instead some variation on *containing* something – like a `.git` subdirectory, or a `Makefile.PL` (in Catalyst’s case), or some other such marker that basically says “this is the root of a particular kind of subtree”. If you know what name you are looking for, it seems to me that typically you also know what level you’re going to find it at, either directly or from the root of the subtree.

**Comment by masterbee** [comment]
@ap  I was not say that it would make it simpler, I was saying it would be cleaner and more robust. The cleaner is simply because an integer value for parent is a bit nebulous while text makes it clearer for developer what is the target parent, IMHO. 

More robust, simply in the fact that it is more portable, and you would not have to change the integer if you change the location of the script ( barring it is still a child of that parent ).

Make more sense?

**Comment by xdg** [comment]
Thank you for your thoughts and contribution.  However, on reflection, I don't think a parent name search feature is a good addition to Path::Tiny.  In my opinion, it wouldn't be "Tiny" enough.

The need for "find superparent by basename" seems to be very niche and the code to implement it application-side is an easy loop as you showed.  I think this sort of needle-in-haystack problem is best left to end users who know the right way to match.
