### ISSUE TITLE
Poor interaction with IO::Async::Function

### ISSUE THREAD

**Issue by lechner** [dagolden/Path-Tiny#224]
When switching `lintian` to `IO::Async` (from a combination of IPC frameworks) I had to use a single call to `append_utf8` when appending multiple segments to a file. Successive calls blocked because the `flock` was not lifted by the call to `close` [here](https://metacpan.org/source/DAGOLDEN/Path-Tiny-0.108/lib/Path/Tiny.pm#L551). Inserting `flock($fh, LOCK_UN);` just before that solves the problem, but `IO::Async` may well be at fault, especially because the problem does not arise with `IO::Async::Process`.

The issue is also solved by setting and unsetting `PERL_PATH_TINY_NO_FLOCK` around the calls to `attach_utf8` [here](https://salsa.debian.org/lintian/lintian/blob/master/lib/Test/Lintian/ConfigFile.pm#L129-135).

Based on the man page for [`flock(2)`](https://linux.die.net/man/2/flock) it seems that `close` does not release the lock because the file descriptor is open elsewhere. Maybe `IO::Async` keeps a copy for scheduling or cleanup purposes?

As far as I can tell, Debian defaults to the `fork` detachment model in `IO::Async::Routine`.

Thank you for providing this neat little library. I like it very much.

**Comment by xdg** [comment]
The problem I see is that there's no guarantee that all data is flushed until close is called, so releasing the lock before close is risky. While it might be possible to manually implement that, I don't know how portable it would be.  I'm going to close this as "not Tiny".  Path::Tiny may not be the right tool in async situations where something else is holding the file handle open.
