### ISSUE TITLE
t/zzz-spec.t fails on perl 5.29.10 @ MSWin

### ISSUE THREAD

**Issue by kmx** [dagolden/Path-Tiny#228]
The failure looks like this:
```
t/zzz-spec.t ...................... 1/?
#   Failed test 'path('//a/b/c/.../d')'
#   at t/zzz-spec.t line 210.
#          got: '//a/b/c/.../d'
#     expected: '//a/b/d'

#   Failed test 'path('/a/b/c/.../d')'
#   at t/zzz-spec.t line 210.
#          got: '/a/b/c/.../d'
#     expected: '/a/d'
# Looks like you failed 2 tests of 87.
t/zzz-spec.t ...................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/87 subtests

Test Summary Report
-------------------
t/zzz-spec.t                    (Wstat: 512 Tests: 87 Failed: 2)
  Failed tests:  73, 75
  Non-zero exit status: 2
Files=27, Tests=1729, 34 wallclock secs ( 1.16 usr +  0.25 sys =  1.41 CPU)
Result: FAIL
```

**Comment by parmstro64** [comment]
I have the same issue on Win32 with Perl 5.30.0:

[18:21:59] t/zzz-spec.t ...................... 52/?
#   Failed test 'path('//a/b/c/.../d')'
#   at t/zzz-spec.t line 210.
#          got: '//a/b/c/.../d'
#     expected: '//a/b/d'

#   Failed test 'path('/a/b/c/.../d')'
#   at t/zzz-spec.t line 210.
#          got: '/a/b/c/.../d'
#     expected: '/a/d'
# Looks like you failed 2 tests of 87.
[18:21:59] t/zzz-spec.t ...................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/87 subtests
[18:22:01]

Test Summary Report
-------------------
t/zzz-spec.t                    (Wstat: 512 Tests: 87 Failed: 2)
  Failed tests:  73, 75
  Non-zero exit status: 2
Files=27, Tests=1730, 32 wallclock secs ( 1.34 usr +  0.17 sys =  1.52 CPU)
Result: FAIL
Failed 1/27 test programs. 2/1730 subtests failed.
gmake: *** [Makefile:909: test_dynamic] Error 2


Summary of my perl5 (revision 5 version 30 subversion 0) configuration:
  Platform:
    osname=MSWin32
    osvers=6.1
    archname=MSWin32-x86-multi-thread-64int
    uname='Win32 perl 5.30.0 Sun Aug 18 16:55:45 2019 i686'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=undef
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL
_IMPLICIT_SYS -DWIN32_NO_REGISTRY -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mm
s-bitfields -I"e:\usr\mingw32\include" -I"e:\usr\mingw32\i686-w64-mingw32\include"'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='7.1.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"e:\usr\lib\CORE" -L"e:\usr\mingw32\lib"'
    libpth=e:\usr\mingw32\lib e:\usr\mingw32\i686-w64-mingw32\lib e:\usr\mingw32\lib\gcc\i686-w64-mingw3
2\7.1.0
    libs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -lole
aut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32
-loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl530.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"e:\usr\lib\CORE" -L"e:\usr\mingw32\lib"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_NO_REGISTRY
    USE_PERLIO
    USE_PERL_ATOF
    USE_SITECUSTOMIZE
  Built under MSWin32
  Compiled at Sep  1 2019 16:23:57
  @INC:
    E:/usr/site/lib
    E:/usr/vendor/lib
    E:/usr/lib
    .

**Comment by parmstro64** [comment]
[18:21:59] t/zzz-spec.t ...................... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/87 subtests
[18:22:01]

Test Summary Report

t/zzz-spec.t (Wstat: 512 Tests: 87 Failed: 2)
Failed tests: 73, 75
Non-zero exit status: 2
Files=27, Tests=1730, 32 wallclock secs ( 1.34 usr + 0.17 sys = 1.52 CPU)
Result: FAIL
Failed 1/27 test programs. 2/1730 subtests failed.
gmake: *** [Makefile:909: test_dynamic] Error 2

Summary of my perl5 (revision 5 version 30 subversion 0) configuration:
Platform:
osname=MSWin32
osvers=6.1
archname=MSWin32-x86-multi-thread-64int
uname='Win32 perl 5.30.0 Sun Aug 18 16:55:45 2019 i686'
config_args='undef'
hint=recommended
useposix=true
d_sigaction=undef
useithreads=define
usemultiplicity=define
use64bitint=define
use64bitall=undef
uselongdouble=undef
usemymalloc=n
default_inc_excludes_dot=undef
bincompat5005=undef
Compiler:
cc='gcc'
ccflags =' -s -O2 -DWIN32 -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL
_IMPLICIT_SYS -DWIN32_NO_REGISTRY -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mm
s-bitfields -I"e:\usr\mingw32\include" -I"e:\usr\mingw32\i686-w64-mingw32\include"'
optimize='-s -O2'
cppflags='-DWIN32'
ccversion=''
gccversion='7.1.0'
gccosandvers=''
intsize=4
longsize=4
ptrsize=4
doublesize=8
byteorder=12345678
doublekind=3
d_longlong=define
longlongsize=8
d_longdbl=define
longdblsize=12
longdblkind=3
ivtype='long long'
ivsize=8
nvtype='double'
nvsize=8
Off_t='long long'
lseeksize=8
alignbytes=8
prototype=define
Linker and Libraries:
ld='g++'
ldflags ='-s -L"e:\usr\lib\CORE" -L"e:\usr\mingw32\lib"'
libpth=e:\usr\mingw32\lib e:\usr\mingw32\i686-w64-mingw32\lib e:\usr\mingw32\lib\gcc\i686-w64-mingw3
2\7.1.0
libs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -lole
aut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32
-loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
libc=
so=dll
useshrplib=true
libperl=libperl530.a
gnulibc_version=''
Dynamic Linking:
dlsrc=dl_win32.xs
dlext=dll
d_dlsymun=undef
ccdlflags=' '
cccdlflags=' '
lddlflags='-mdll -s -L"e:\usr\lib\CORE" -L"e:\usr\mingw32\lib"'

Characteristics of this binary (from libperl):
Compile-time options:
HAS_TIMES
HAVE_INTERP_INTERN
MULTIPLICITY
PERLIO_LAYERS
PERL_COPY_ON_WRITE
PERL_DONT_CREATE_GVSV
PERL_IMPLICIT_CONTEXT
PERL_IMPLICIT_SYS
PERL_MALLOC_WRAP
PERL_OP_PARENT
PERL_PRESERVE_IVUV
USE_64_BIT_INT
USE_ITHREADS
USE_LARGE_FILES
USE_LOCALE
USE_LOCALE_COLLATE
USE_LOCALE_CTYPE
USE_LOCALE_NUMERIC
USE_LOCALE_TIME
USE_NO_REGISTRY
USE_PERLIO
USE_PERL_ATOF
USE_SITECUSTOMIZE
Built under MSWin32
Compiled at Sep 1 2019 16:23:57
@inc:
E:/usr/site/lib
E:/usr/vendor/lib
E:/usr/lib
.
