### ISSUE TITLE
canonpath does not understand Windows UNC paths

### ISSUE THREAD

**Issue by Haf-Linger** [dagolden/Path-Tiny#229]
`use Path::Tiny; `
`my $path = path('\\server\share\folder\file.ext')->canonpath;`  
`say $path;`
This will give you back the totally unusable path:
\server\share\folder\file.ext

Got this result using Tiny::Path version 1.04

**Comment by Haf-Linger** [comment]
silly mistake on my part - sorry

**Comment by ap** [comment]
Backslashes as path component separators, the gift that keeps on giving…
