### ISSUE TITLE
Aliases for making copy/move more readable

### ISSUE THREAD

**Issue by polettix** [dagolden/Path-Tiny#234]
Hi! First and foremost, thanks for this module: I find it great.

I always get some shivers when I read this:

```perl
$foo->copy($bar);
```

Is `$foo` copied onto `$bar` or the other way around? I always feel the urge to double check on the docs (at least, after a week or so that I don't use it).

It would be nice to have an alias that makes the whole thing more readable, like:

```perl
$foo->copy_to($bar);
```

The same goes for `move`/`move_to`.

Whatever you decide to do with this issue... thanks for your time 😄

**Comment by xdg** [comment]
On reflection, I think more API changes/aliases just confuse more people and make code more Path::Tiny version centric.  Closing.

**Comment by polettix** [comment]
Thanks for considering :smile:
