### ISSUE TITLE
move method should have a fallback option that uses copy/remove

### ISSUE THREAD

**Issue by robrwo** [dagolden/Path-Tiny#237]
The `move` method does not work when the destination is on another device. It would be good to have a fallback option to use copy and remove, e.g.

```perl
$file->move( $dest, { copy_on_fail => 1 } );
```
If the call to rename fails, and `copy_on_fail` is true, then it tries to use copy and remove.

Alternatively, you could have a `copy` option that determines whether it uses copy/remove: false (default) for using rename, another value for copy on fail, or always.

**Comment by adouglas1-godaddy** [comment]
`copy` already uses `File::Copy::copy`; why not do the same for `move`, since `File::Copy::move` already handles this?

**Comment by atoomic** [comment]
Looks like #250 needs to be rebased
@xdg would appreciate your feedback on it

**Comment by atoomic** [comment]
Rebased and resubmitted as #260 hopefully this will get more traction :-)
