### ISSUE TITLE
Completely fails most tests with Window 10 and Perl 5.34.0

### ISSUE THREAD

**Issue by SteelBlueVision** [dagolden/Path-Tiny#240]

**Comment by xdg** [comment]
Hi.  That doesn't give much to go on.  Could you please provide more details?  What Perl vendor are you using (e.g. Strawberry, ActiveState, etc.)?  What is the output of `perl -V`?  What version of Path-Tiny is giving you trouble?  How are you running the test (e.g. cpan client, manual, etc.)?  Can you provide the full output of test run?

**Comment by xdg** [comment]
Closed for lack of details.
