### ISSUE TITLE
Why not using POSIX::ceil instead of your own custom _ceil() function?

### ISSUE THREAD

**Issue by robrwo** [dagolden/Path-Tiny#245]
POSIX is a core module. Why not just use POSIX::ceil instead of creating your own _ceil function

**Comment by xdg** [comment]
Loading POSIX increases Path::Tiny's memory footprint by 10%.  Seemed unnecessary for what is likely to be a rarely used method.  Path::Tiny doesn't universally optimize for performance -- only around the hottest part of the code, like path manipulation and slurping/spewing.

**Comment by robrwo** [comment]
Fair enough. Might be worth adding a one-line comment about that.
