### ISSUE TITLE
Missing version info for module 'Digest'

### ISSUE THREAD

**Issue by wollmers** [dagolden/Path-Tiny#248]
Same behaviour on Perl 5.32.0, 5.32.1, 534.1

perlbrew is latest, cpanm is latest.

```
$ cpanm Path::Tiny
--> Working on Path::Tiny
Fetching http://www.cpan.org/authors/id/D/DA/DAGOLDEN/Path-Tiny-0.122.tar.gz ... OK
Configuring Path-Tiny-0.122 ... OK
==> Found dependencies: Digest
--> Working on Digest
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/Digest-1.20.tar.gz ... OK
Configuring Digest-1.20 ... OK
Building and testing Digest-1.20 ... OK
Successfully installed Digest-1.20
! Installing the dependencies failed: Missing version info for module 'Digest'
! Bailing out the installation for Path-Tiny-0.122.
1 distribution installed
```

It's not clear, what exactly goes wrong.

Work around was to download the tar.gz, comment out the dependencies in `Makefile.PL` and install with `cpanm -f -n .`.

**Comment by wollmers** [comment]
Related https://github.com/Dual-Life/digest/issues/9

**Comment by xdg** [comment]
What version of cpanm?

**Comment by xdg** [comment]
I am unable to reproduce this with cpanm 1.7046.

I've also built a brand new Perl 5.34.1 with plenv, installed cpanm, and started my "normal" module set install, which gets Path::Tiny very early.  No Path::Tiny dependencies are installed prior to Path::Tiny being installed and it installs correctly, without picking up `Digest` as a needed dependency.

Unless you can provide a step-by-step reproduction,  I have to conclude that you have a broken Perl installation.

**Comment by wollmers** [comment]
Whats your "normal" module set install?

My version of `cpanm`:

```
$ cpanm -v
cpanm (App::cpanminus) 1.7046 on perl 5.034001 built for darwin-2level
Work directory is /Users/helmut/.cpanm/work/1653292080.15255
You have make /usr/bin/make
You have LWP 6.66
You have /usr/bin/tar: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
You have /usr/bin/unzip
Usage: cpanm [options] Module [...]
```

> without picking up Digest as a needed dependency

OK, in your view `Digest` should not be a required dependency. That's an important information we can check against.

`Digest` is defined as required in https://metacpan.org/release/DAGOLDEN/Path-Tiny-0.122/source/cpanfile

```
# This file is generated by Dist::Zilla::Plugin::CPANFile v6.024
# Do not edit this file directly. To change prereqs, edit the `dist.ini` file.
 
requires "Carp" => "0";
requires "Cwd" => "0";
requires "Digest" => "1.03";
[...]
```

also in https://metacpan.org/release/DAGOLDEN/Path-Tiny-0.122/source/META.json
and in https://metacpan.org/release/DAGOLDEN/Path-Tiny-0.122/source/Makefile.PL under `%FallbackPrereqs`.

```
unless ( eval { ExtUtils::MakeMaker->VERSION(6.63_03) } ) {
  delete $WriteMakefileArgs{TEST_REQUIRES};
  delete $WriteMakefileArgs{BUILD_REQUIRES};
  $WriteMakefileArgs{PREREQ_PM} = \%FallbackPrereqs;
}
```

Maybe there is a problem in combination with `ExtUtils::MakeMaker`:

```
$ cpanm --info ExtUtils::MakeMaker
BINGOS/ExtUtils-MakeMaker-7.64.tar.gz

$ perl -e  'use ExtUtils::MakeMaker; print ExtUtils::MakeMaker->VERSION,"\n";'
7.62
```

But then it should handle it better.

**Comment by wollmers** [comment]
Boiled it down more, and IMHO can exclude a problem in `Path::Tiny`.

Seems a problem of `cpanm`, maybe in combination with `perlbrew`, as `Digest` isn't recognised as installed (but other modules like `Module::Metadata` recognise it correctly.

```
$ cpanm Digest; cpanm Digest
--> Working on Digest
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/Digest-1.20.tar.gz ... OK
Configuring Digest-1.20 ... OK
Building and testing Digest-1.20 ... OK
Successfully installed Digest-1.20
1 distribution installed
--> Working on Digest
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/Digest-1.20.tar.gz ... OK
Configuring Digest-1.20 ... OK
Building and testing Digest-1.20 ... OK
Successfully installed Digest-1.20
1 distribution installed

$ cpanm Path::Tiny
Path::Tiny is up to date. (0.122)
```

**Comment by xdg** [comment]
Thanks for digging into the root causes!
