### ISSUE TITLE
IO::All assert() function

### ISSUE THREAD

**Issue by bokutin** [dagolden/Path-Tiny#251]
Hello.
In IO::All we use io("$dir/$file")->assert->print($data), which will mkpath if the directory is missing.
In Path::Tiny, touchpath is a similar function, but without touch?
I know this is a very common need, but are there any plans to include it in Path::Tiny?

**Comment by xdg** [comment]
I don't see why "touch" is a problem if the file is going to be overwritten anyway.

In any case, I would not include such a feature, as the non-touch version is trivially done with existing methods.

**Comment by bokutin** [comment]
Thanks for the response!

**Comment by bokutin** [comment]
I'm sure it's a very minor difference.
I can't think of any situation where I would want to do a touch.
Sorry if I am rude.
