### ISSUE TITLE
[Feature] `set_parent` method

### ISSUE THREAD

**Issue by rwp0** [dagolden/Path-Tiny#253]
Currently the [`parent`](https://metacpan.org/pod/Path::Tiny#parent) method returns the parent directory path (optionally to n-th degree with a numeric argument).

Can we have a method similar to [`child`](https://metacpan.org/pod/Path::Tiny#child) that would set the parent instead?

I needed such a method for my script, and didn't find it reading the [documentation](https://metacpan.org/pod/Path::Tiny).

For instance:
```perl
use Path::Tiny;
my $extension = path 'php/20131226/curl.so';
my $path = $extension -> set_parent('/usr/local/lib');
say $path; # /usr/local/lib/php/20131226/curl.so
```

Since it mostly just prepends (being the reverse of `child`), shouldn't be hard to implement I think.

Thank you for the attention.

**Comment by xdg** [comment]
I don't think this needs a new method.  There are a couple ways to do it, depending on the semantics you want:

```
# add the extension as child of the new parent
$path = path("/usr/local/lib")->child($extension);

# root a relative extension under an absolute path
$path = $extension->absolute("/usr/local/lib");
```
