### ISSUE TITLE
mkdir fails if the directory exists

### ISSUE THREAD

**Issue by robrwo** [dagolden/Path-Tiny#259]
This code using `mkdir` fails when the directory already exists:
```perl
use Path::Tiny;
$dir = path("./foobar")->mkdir; 
$dir; $dir->mkdir;
```

That is because no directories are created, so the underlying `make_path` function that it uses returns nothing.  It's not an error condition.

But comparing it to `mkdir -p` is wrong, because that function will not fail if the directory exists/

I can change the code to check if the directories exist,
```perl
$dir->mkpath unless $dir->is_dir;
```
but this seems like a step backwards. I now have to modify code that used `mkpath` to use `mkdir` along with a check if the directory exists.  It also means that I cannot chain calls to `mkdir` since it might fail.

I would recommend modifying `mkdir` to ignore when no paths are created, but add an option to throw an error if nothing is created.

**Comment by xdg** [comment]
Good catch. Pushing a fix now.
