### ISSUE TITLE
Should mkpath be renamed?

### ISSUE THREAD

**Issue by dagolden** [dagolden/Path-Tiny#28]
It doesn't follow same naming pattern as other methods.

It echoes File::Path, but should really be "make_path" for consistency with "remove_tree".

Possibly, it should be "make_tree" for proper parallelism.

**Comment by xsawyerx** [comment]
I like `make_path`. You can keep `mkpath` for compatibility (either with older versions of `Path::Tiny` or with `File::Spec`), and possibly remove later.

**Comment by ap** [comment]
> Possibly, it should be "make_tree" for proper parallelism.

They are not parallels, though: `remove_tree` really does remove an entire tree, whereas it‘s odd to call `foo/bar/baz/quux` a“tree. It’s just a single chain of subdirectories… basically, well, a path. So in that respect the names seem fine to me.

----

For me it’s the `remove_tree` name I don’t like: it seems needlessly verbose. I would favour renaming that one to `rmtree` (while leaving an alias in place essentially forever yada backcompat yada). I’ve rewritten some shell scripts in Perl with the aid of Path::Tiny before and the fact I had to spell it out over and over in densely FS-modifying code was irritating (to read, not just write).

Or possibly both synonyms for both of the methods should go in? I can see that spelling things out in less dense code looks nicer, and the code-wise cost is trivial. So the question is whether this increases the burden on the maintenance programmer later… on which I learn towards no.

**Comment by xdg** [comment]
`mkpath` was deprecated in 0.125
