### ISSUE TITLE
Feature request: Get file/directory permissions

### ISSUE THREAD

**Issue by scottchiefbaker** [dagolden/Path-Tiny#295]
Recently I need to determine if a file was world readable which requires fetching the permissions, and masking out the "other" permissions from the result. I ended up with this:

```
sub get_file_permissions {
	my $file = shift();

	my @x    = stat($file);
	my $mode = $x[2];

	my $user  = ($mode & 0700) >> 6;
	my $group = ($mode & 0070) >> 3;
	my $other = ($mode & 0007);

	my @ret = ($user, $group, $other);

	return @ret;
}
```

Is this something you would consider for inclusion in `Path::Tiny`? I can work on a PR if this is something you would be willing to land.

**Comment by karenetheridge** [comment]
Perhaps an interface like `->permissions('user')`, `->permissions('group')`..?

**Comment by scottchiefbaker** [comment]
That's not too bad... Alternately we could do something like

```
$bool = $path->readable('user');
$bool = $path->writable('group');
$bool = $path->executable('other');
```

**Comment by scottchiefbaker** [comment]
This ended up being not as complicated as I thought so I coded it up and landed a PR for it.

**Comment by xdg** [comment]
NB. PR is #296 .

**Comment by xdg** [comment]
Sorry it's taken me a while to get to this. After some considerations, I'm going to pass on this API extension.  Path::Tiny already provides `stat`, so these sorts of checks are relatively straightforward uses of `$path->stat->mode`.

**Comment by karenetheridge** [comment]
> these sorts of checks are relatively straightforward uses of `$path->stat->mode`.

Some examples of that might be a nice addition to the documentation entry for the `stat` method.
