### ISSUE TITLE
idea for enhancement: encodings for filenames

### ISSUE THREAD

**Issue by vsespb** [dagolden/Path-Tiny#48]
1. allow to specify encodings for filenames in filesystem (including UTF-8).
2. this is useful even if encoding is UTF-8 - it would fixes problem working with downgraded vs upgraded Latin1:  http://perldoc.perl.org/perlunicode.html "When Unicode Does Not Happen"

**Comment by xdg** [comment]
On reflection, I'm going to close this.  As a Tiny module, Path::Tiny doesn't need to solve every edge case.  Since there is no easy, obvious solution, users with this problem can chose another module or handle it manually.
