### ISSUE TITLE
How to handle "could not map to Unicode" warnings?

### ISSUE THREAD

**Issue by dagolden** [dagolden/Path-Tiny#57]
Options:
- fatalize them
- leave them alone
- catch them in a `__WARN__` handler and ignore them

If we're trying to read UTF-8 and the file isn't UTF-8, the "correct" thing to do might be to throw an error instead of allowing it through.  Both :utf8 and :encoding(UTF-8) can have the "utf8" category fatalized, but that might be too restrictive if the warning occurs in common cases when the substitution character would be put in.

The other extreme is to catch warnings and ignore, since users are getting exactly what they asked for and it's not our fault if that's not right.  We can turn off utf8 warnings for :utf8, but it's not respected by encoding(UTF-8) so we would need a `__WARN__` handler.

Since I don't know the right answer, I'll do nothing for now but leave this as a placeholder.

**Comment by ilmari** [comment]
`PerlIO::encoding` takes its fallback  behaviour from the value of `$PerlIO::encoding::fallback` when the layer is applied, so you can set that to one of the `Encoding::FB_*` values.

**Comment by xdg** [comment]
On reflection, I'm going to close this "won't fix".  Users can disable warnings in various ways if as a Tiny module, I don't think it's the right move to add callback overhead handling malformed characters.
