### ISSUE TITLE
Should there be an option for faster, "unsafe" operations?

### ISSUE THREAD

**Issue by dagolden** [dagolden/Path-Tiny#8]
I think safe is a good default, busing flocking and/or atomic writes is slow.

Give a faster unsafe option?  Or is that not TIny?

**Comment by dotandimet** [comment]
+1
We use a big storage device over NFS, and when it is under heavy load, a simple append via Path::Tiny will hang a script for undetermined amounts of time.

**Comment by xdg** [comment]
On reflection, I think "safe by default" is the right goal for Path::Tiny.

**Comment by ap** [comment]
Was that ever in question? The question here would seem to me to have been whether there should be an *option* to ask for unsafe operation – not as a default, but explicitly. “Safe-by-default is the right goal” does not answer that…
