### ISSUE TITLE
Path traversals inside tempdirs should perhaps keep references to that tempdir

### ISSUE THREAD

**Issue by kentfredric** [dagolden/Path-Tiny#97]
I've seen a bunch of problems that occur with code like this:

```perl
my $x = Path::Tiny->tempdir();
my $child = $x->child("foo");
$child->spew("content");
return $child;
```

Or similar. Essentially, you still have an object you're passing around that pertains to a file in a temporary directory, but due to the mechanism of the temporary directory being "delete on GC" + child nodes not referring to the temp directory, the child quickly becomes invalid.

Ideally, the temporary directory should only be GC'd when all the children no longer have anyone using them.

And it seems plausible that `->child` could potentially copy `$_[0]->[TEMP]` around without it having unwanted side effects.

You could potentially do that too for `->absolute` and `->relative` , which I've occasionally made the mistake of doing:

```perl
  my $x = Path::Tiny->tempdir->absolute;
```
Which of course yields nothing useful. ( It is indeed redundant because `tempdir` is already absolute, but I don't manage to remember this )

**Comment by dagolden** [comment]
Closing this as "won't fix"
